apiVersion: v1
data:
  words.sql: |
    CREATE TABLE nouns (word TEXT NOT NULL);
    CREATE TABLE verbs (word TEXT NOT NULL);
    CREATE TABLE adjectives (word TEXT NOT NULL);

    INSERT INTO nouns(word) VALUES
      ('cloud'),
      ('elephant'),
      ('flødebolle'),
      ('smørrebrød');

    INSERT INTO verbs(word) VALUES
      ('will drink'),
      ('smashes'),
      ('invites'),
      ('hides'),
      ('will ship');

    INSERT INTO adjectives(word) VALUES
      ('the exquisite'),
      ('a pink'),
      ('the røtten'),
      ('a red'),
      ('the serverless'),
      ('the deliciøus');
kind: ConfigMap
metadata:
  name: db-schema
